language: node_js
node_js:
- '6'
- 'node'
env:
  global:
  - secure: "ZLO8+tomNwHKqXTpHKYmTl8SH8WNGSGaeuKxoFDOUmpSL1FiUBkmAws4pJ6aoScztQidFdnIJ9F/Z5Dn6DUuAzaZmNJEZubyCP+a2hmIuUYTR9vYv9ktIdin1Ekq3AdJIBzb705uYeUeKewItx4vDDTbkGLSuxjh/EjVAoGX/yw="
  matrix:
  - MAILOSAUR_BASE_URL=https://mailosaur.com/ MAILOSAUR_SMTP_HOST=mailosaur.io
  - MAILOSAUR_BASE_URL=https://next.mailosaur.com/ MAILOSAUR_SMTP_HOST=ms-smtp.uk
notifications:
  slack: mailosaur:CsJ9RruwjqHPKr1Iugk8GDtX
