/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a EmailAddress.
 */
class EmailAddress {
  /**
   * Create a EmailAddress.
   * @member {string} [address]
   * @member {string} [name]
   */
  constructor() {
  }

  /**
   * Defines the metadata of EmailAddress
   *
   * @returns {object} metadata of EmailAddress
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'EmailAddress',
      type: {
        name: 'Composite',
        className: 'EmailAddress',
        modelProperties: {
          address: {
            required: false,
            serializedName: 'address',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = EmailAddress;
