/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.SpamAssassinRule = require('./spamAssassinRule');
exports.SpamCheckResult = require('./spamCheckResult');
exports.MailosaurError = require('./mailosaurError');
exports.Link = require('./link');
exports.Image = require('./image');
exports.EmailData = require('./emailData');
exports.EmailAddress = require('./emailAddress');
exports.Attachment = require('./attachment');
exports.Email = require('./email');
exports.SearchCriteria = require('./searchCriteria');
exports.Message = require('./message');
exports.ForwardingRule = require('./forwardingRule');
exports.Server = require('./server');
exports.ServerCreateOptions = require('./serverCreateOptions');
