/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a Message.
 */
class Message {
  /**
   * Create a Message.
   * @member {object} [html]
   * @member {array} [html.links]
   * @member {array} [html.images]
   * @member {string} [html.body]
   * @member {object} [text]
   * @member {array} [text.links]
   * @member {array} [text.images]
   * @member {string} [text.body]
   * @member {object} [headers]
   * @member {string} [subject]
   * @member {array} [from]
   * @member {array} [to]
   * @member {array} [attachments]
   * @member {date} received
   * @member {string} [senderhost]
   * @member {string} [server]
   * @member {uuid} id
   */
  constructor() {
  }

  /**
   * Defines the metadata of Message
   *
   * @returns {object} metadata of Message
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Message',
      type: {
        name: 'Composite',
        className: 'Message',
        modelProperties: {
          html: {
            required: false,
            serializedName: 'html',
            type: {
              name: 'Composite',
              className: 'EmailData'
            }
          },
          text: {
            required: false,
            serializedName: 'text',
            type: {
              name: 'Composite',
              className: 'EmailData'
            }
          },
          headers: {
            required: false,
            serializedName: 'headers',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'ObjectElementType',
                  type: {
                    name: 'Object'
                  }
              }
            }
          },
          subject: {
            required: false,
            serializedName: 'subject',
            type: {
              name: 'String'
            }
          },
          from: {
            required: false,
            serializedName: 'from',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'EmailAddressElementType',
                  type: {
                    name: 'Composite',
                    className: 'EmailAddress'
                  }
              }
            }
          },
          to: {
            required: false,
            serializedName: 'to',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'EmailAddressElementType',
                  type: {
                    name: 'Composite',
                    className: 'EmailAddress'
                  }
              }
            }
          },
          attachments: {
            required: false,
            serializedName: 'attachments',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'AttachmentElementType',
                  type: {
                    name: 'Composite',
                    className: 'Attachment'
                  }
              }
            }
          },
          received: {
            required: true,
            serializedName: 'received',
            type: {
              name: 'DateTime'
            }
          },
          senderhost: {
            required: false,
            serializedName: 'senderhost',
            type: {
              name: 'String'
            }
          },
          server: {
            required: false,
            serializedName: 'server',
            type: {
              name: 'String'
            }
          },
          id: {
            required: true,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Message;
